apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: nginx
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 13.2.10
  destination:
    namespace: {{.Values.namespace}}
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
